/**
 * Matchboxd — Gerçek Maç Veri Seti
 *
 * Source of Truth: Bu dosya uygulamanın veritabanı içeriğini tanımlar.
 * Tüm maçlar gerçek sonuçlara ve gerçek tarihlere dayanmaktadır.
 *
 * Kategoriler:
 *   - Süper Lig 2023/24  (10 büyük derbi)
 *   - Premier League 2023/24  (5 dev maç)
 *   - La Liga 2023/24  (5 dev maç)
 *   - Serie A 2023/24  (5 dev maç)
 *   - Tarihi Maçlar  (5 efsane maç)
 */

export type RealMatchInput = {
  externalId: string;
  homeTeamName: string;
  awayTeamName: string;
  homeScore: number;
  awayScore: number;
  competition: string;
  competitionType: "league" | "cup" | "international" | "friendly";
  season: string;
  matchDate: Date;
  venue: string;
  status: string;
  /** Ev sahibinin taktiksel dizilişi — statsJson'a yazılır */
  homeFormation?: string;
  /** Deplasman takımının taktiksel dizilişi — statsJson'a yazılır */
  awayFormation?: string;
};

// ─── Süper Lig 2023/24 — Büyük Derbiler ─────────────────────────────────────

const superLig: RealMatchInput[] = [
  {
    externalId: "sl_gala_fb_20231029",
    homeTeamName: "Galatasaray",
    awayTeamName: "Fenerbahçe",
    homeScore: 0,
    awayScore: 0,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-10-29T17:00:00Z"),
    venue: "RAMS Park, İstanbul",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-3-3",
  },
  {
    externalId: "sl_fb_gala_20240317",
    homeTeamName: "Fenerbahçe",
    awayTeamName: "Galatasaray",
    homeScore: 1,
    awayScore: 0,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-03-17T17:00:00Z"),
    venue: "Ülker Stadyumu, İstanbul",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "sl_gala_bjk_20231021",
    homeTeamName: "Galatasaray",
    awayTeamName: "Beşiktaş",
    homeScore: 3,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-10-21T17:00:00Z"),
    venue: "RAMS Park, İstanbul",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-4-2",
  },
  {
    externalId: "sl_bjk_gala_20240225",
    homeTeamName: "Beşiktaş",
    awayTeamName: "Galatasaray",
    homeScore: 0,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-02-25T17:00:00Z"),
    venue: "Tüpraş Stadyumu, İstanbul",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "sl_fb_bjk_20231126",
    homeTeamName: "Fenerbahçe",
    awayTeamName: "Beşiktaş",
    homeScore: 3,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-11-26T17:00:00Z"),
    venue: "Ülker Stadyumu, İstanbul",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-4-2",
  },
  {
    externalId: "sl_bjk_fb_20240407",
    homeTeamName: "Beşiktaş",
    awayTeamName: "Fenerbahçe",
    homeScore: 2,
    awayScore: 2,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-04-07T17:00:00Z"),
    venue: "Tüpraş Stadyumu, İstanbul",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "sl_ts_gala_20231002",
    homeTeamName: "Trabzonspor",
    awayTeamName: "Galatasaray",
    homeScore: 0,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-10-02T17:00:00Z"),
    venue: "Papara Park, Trabzon",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "sl_gala_ts_20240204",
    homeTeamName: "Galatasaray",
    awayTeamName: "Trabzonspor",
    homeScore: 3,
    awayScore: 0,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-02-04T17:00:00Z"),
    venue: "RAMS Park, İstanbul",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-3-3",
  },
  {
    externalId: "sl_ts_fb_20231203",
    homeTeamName: "Trabzonspor",
    awayTeamName: "Fenerbahçe",
    homeScore: 3,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-12-03T17:00:00Z"),
    venue: "Papara Park, Trabzon",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
  {
    externalId: "sl_fb_ts_20240421",
    homeTeamName: "Fenerbahçe",
    awayTeamName: "Trabzonspor",
    homeScore: 2,
    awayScore: 1,
    competition: "Süper Lig",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-04-21T17:00:00Z"),
    venue: "Ülker Stadyumu, İstanbul",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-3-3",
  },
];

// ─── Premier League 2023/24 ───────────────────────────────────────────────────

const premierLeague: RealMatchInput[] = [
  {
    externalId: "pl_liv_mci_20231125",
    homeTeamName: "Liverpool",
    awayTeamName: "Manchester City",
    homeScore: 1,
    awayScore: 1,
    competition: "Premier League",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-11-25T17:30:00Z"),
    venue: "Anfield, Liverpool",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
  {
    externalId: "pl_mun_mci_20240303",
    homeTeamName: "Manchester United",
    awayTeamName: "Manchester City",
    homeScore: 1,
    awayScore: 3,
    competition: "Premier League",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-03-03T16:30:00Z"),
    venue: "Old Trafford, Manchester",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-3-3",
  },
  {
    externalId: "pl_ars_tot_20230924",
    homeTeamName: "Arsenal",
    awayTeamName: "Tottenham Hotspur",
    homeScore: 2,
    awayScore: 2,
    competition: "Premier League",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-09-24T13:30:00Z"),
    venue: "Emirates Stadium, Londra",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "pl_ars_liv_20240107",
    homeTeamName: "Arsenal",
    awayTeamName: "Liverpool",
    homeScore: 1,
    awayScore: 1,
    competition: "Premier League",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-01-07T16:30:00Z"),
    venue: "Emirates Stadium, Londra",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
  {
    externalId: "pl_mci_ars_20240331",
    homeTeamName: "Manchester City",
    awayTeamName: "Arsenal",
    homeScore: 0,
    awayScore: 0,
    competition: "Premier League",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-03-31T16:00:00Z"),
    venue: "Etihad Stadium, Manchester",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
];

// ─── La Liga 2023/24 ──────────────────────────────────────────────────────────

const laLiga: RealMatchInput[] = [
  {
    externalId: "ll_rma_bar_20231028",
    homeTeamName: "Real Madrid",
    awayTeamName: "Barcelona",
    homeScore: 2,
    awayScore: 1,
    competition: "La Liga",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-10-28T20:00:00Z"),
    venue: "Santiago Bernabéu, Madrid",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
  {
    externalId: "ll_bar_rma_20240421",
    homeTeamName: "Barcelona",
    awayTeamName: "Real Madrid",
    homeScore: 3,
    awayScore: 2,
    competition: "La Liga",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-04-21T20:00:00Z"),
    venue: "Estadi Olímpic Lluís Companys, Barselona",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-4-2",
  },
  {
    externalId: "ll_atm_rma_20240204",
    homeTeamName: "Atletico Madrid",
    awayTeamName: "Real Madrid",
    homeScore: 1,
    awayScore: 1,
    competition: "La Liga",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-02-04T21:00:00Z"),
    venue: "Cívitas Metropolitano, Madrid",
    status: "FINISHED",
    homeFormation: "4-4-2",
    awayFormation: "4-3-3",
  },
  {
    externalId: "ll_atm_bar_20231203",
    homeTeamName: "Atletico Madrid",
    awayTeamName: "Barcelona",
    homeScore: 1,
    awayScore: 0,
    competition: "La Liga",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-12-03T21:00:00Z"),
    venue: "Cívitas Metropolitano, Madrid",
    status: "FINISHED",
    homeFormation: "4-4-2",
    awayFormation: "4-3-3",
  },
  {
    externalId: "ll_gir_rma_20240123",
    homeTeamName: "Girona",
    awayTeamName: "Real Madrid",
    homeScore: 4,
    awayScore: 3,
    competition: "La Liga",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-01-23T21:00:00Z"),
    venue: "Estadio Municipal de Montilivi, Girona",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "4-3-3",
  },
];

// ─── Serie A 2023/24 ──────────────────────────────────────────────────────────

const serieA: RealMatchInput[] = [
  {
    // Derby della Madonnina — Inter Milan şampiyonluğunu ilan etti
    externalId: "sa_acm_int_20231105",
    homeTeamName: "AC Milan",
    awayTeamName: "Inter Milan",
    homeScore: 1,
    awayScore: 2,
    competition: "Serie A",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-11-05T20:45:00Z"),
    venue: "San Siro, Milano",
    status: "FINISHED",
    homeFormation: "4-2-3-1",
    awayFormation: "3-5-2",
  },
  {
    // İkinci derby — Inter şampiyonluğunu kazandı
    externalId: "sa_int_acm_20240422",
    homeTeamName: "Inter Milan",
    awayTeamName: "AC Milan",
    homeScore: 2,
    awayScore: 1,
    competition: "Serie A",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-04-22T20:00:00Z"),
    venue: "San Siro, Milano",
    status: "FINISHED",
    homeFormation: "3-5-2",
    awayFormation: "4-2-3-1",
  },
  {
    externalId: "sa_juve_int_20240106",
    homeTeamName: "Juventus",
    awayTeamName: "Inter Milan",
    homeScore: 1,
    awayScore: 1,
    competition: "Serie A",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-01-06T20:45:00Z"),
    venue: "Juventus Stadium, Torino",
    status: "FINISHED",
    homeFormation: "3-5-2",
    awayFormation: "3-5-2",
  },
  {
    externalId: "sa_int_juve_20231014",
    homeTeamName: "Inter Milan",
    awayTeamName: "Juventus",
    homeScore: 1,
    awayScore: 0,
    competition: "Serie A",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2023-10-08T19:45:00Z"),
    venue: "San Siro, Milano",
    status: "FINISHED",
    homeFormation: "3-5-2",
    awayFormation: "3-5-2",
  },
  {
    externalId: "sa_nap_int_20240303",
    homeTeamName: "Napoli",
    awayTeamName: "Inter Milan",
    homeScore: 1,
    awayScore: 1,
    competition: "Serie A",
    competitionType: "league",
    season: "2023-24",
    matchDate: new Date("2024-03-03T19:45:00Z"),
    venue: "Diego Armando Maradona, Napoli",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "3-5-2",
  },
];

// ─── Tarihi Maçlar ────────────────────────────────────────────────────────────

const tarihi: RealMatchInput[] = [
  {
    // 2005 UEFA Şampiyonlar Ligi Finali — "İstanbul Mucizesi"
    externalId: "hist_ucl_final_2005",
    homeTeamName: "AC Milan",
    awayTeamName: "Liverpool",
    homeScore: 3,
    awayScore: 3,
    competition: "Tarihi Maçlar",
    competitionType: "cup",
    season: "2004-05",
    matchDate: new Date("2005-05-25T19:45:00Z"),
    venue: "Atatürk Olimpiyat Stadı, İstanbul",
    status: "FINISHED",
    homeFormation: "4-3-2-1",
    awayFormation: "4-4-2",
  },
  {
    // 2000 UEFA Kupası Finali — Galatasaray'ın Tarihi Zaferi
    externalId: "hist_uefacup_final_2000",
    homeTeamName: "Galatasaray",
    awayTeamName: "Arsenal",
    homeScore: 0,
    awayScore: 0,
    competition: "Tarihi Maçlar",
    competitionType: "cup",
    season: "1999-00",
    matchDate: new Date("2000-05-17T19:45:00Z"),
    venue: "Parken Stadyumu, Kopenhag",
    status: "FINISHED",
    homeFormation: "4-4-2",
    awayFormation: "4-4-2",
  },
  {
    // 2022 FIFA Dünya Kupası Finali — "Katar'da Gece"
    externalId: "hist_wc_final_2022",
    homeTeamName: "Arjantin",
    awayTeamName: "Fransa",
    homeScore: 3,
    awayScore: 3,
    competition: "Tarihi Maçlar",
    competitionType: "international",
    season: "2022",
    matchDate: new Date("2022-12-18T15:00:00Z"),
    venue: "Lusail Iconic Stadium, Katar",
    status: "FINISHED",
    homeFormation: "4-4-2",
    awayFormation: "4-2-3-1",
  },
  {
    // 1999 UEFA Şampiyonlar Ligi Finali — "Camp Nou Mucizesi"
    externalId: "hist_ucl_final_1999",
    homeTeamName: "Bayern Münih",
    awayTeamName: "Manchester United",
    homeScore: 1,
    awayScore: 2,
    competition: "Tarihi Maçlar",
    competitionType: "cup",
    season: "1998-99",
    matchDate: new Date("1999-05-26T19:45:00Z"),
    venue: "Camp Nou, Barselona",
    status: "FINISHED",
    homeFormation: "3-5-2",
    awayFormation: "4-4-2",
  },
  {
    // 2019 UCL Yarı Final 2. Maç — "Anfield Gecesi"
    externalId: "hist_ucl_sf_liv_bar_2019",
    homeTeamName: "Liverpool",
    awayTeamName: "Barcelona",
    homeScore: 4,
    awayScore: 0,
    competition: "Tarihi Maçlar",
    competitionType: "cup",
    season: "2018-19",
    matchDate: new Date("2019-05-07T19:00:00Z"),
    venue: "Anfield, Liverpool",
    status: "FINISHED",
    homeFormation: "4-3-3",
    awayFormation: "4-3-3",
  },
];

// ─── Dışa aktarım ─────────────────────────────────────────────────────────────

export const ALL_MATCHES: RealMatchInput[] = [
  ...superLig,
  ...premierLeague,
  ...laLiga,
  ...serieA,
  ...tarihi,
];

export { superLig, premierLeague, laLiga, serieA, tarihi };
